//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BOL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Order
    {
        public int ord_id { get; set; }
        public int it_id { get; set; }
        public int quantity { get; set; }
        public decimal price_per_quantity { get; set; }
        public int bill_id { get; set; }
    
        public virtual Bill_orders Bill_orders { get; set; }
        public virtual Item Item { get; set; }
    }
}
